// Data
export const SET_CRAFTING_SLOT = 'SET_CRAFTING_SLOT'
export const RESET_CRAFTING_SLOT = 'RESET_CRAFTING_SLOT'
export const SET_FIRST_EMPTY_CRAFTING_SLOT = 'SET_FIRST_EMPTY_CRAFTING_SLOT'
export const SET_OUTPUT_SLOT = 'SET_OUTPUT_SLOT'
export const RESET_OUTPUT_SLOT = ''
// Options
export const SET_SHAPE = 'SET_SHAPE'
export const SET_EMPTY_SPACE = 'SET_EMPTY_SPACE'
export const SET_OUTPUT_RECIPE = 'SET_OUTPUT_RECIPE'
// Private
export const TOGGLE_SHOWING_CONTEXT_MENU = 'TOGGLE_SHOWING_CONTEXT_MENU'
export const TOGGLE_SHOWING_COUNT_MENU = 'TOGGLE_SHOWING_COUNT_MENU'