/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesChar123VersionChar125RouteImport } from './routes/recipes.{-$version}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const RecipesChar123VersionChar125Route =
  RecipesChar123VersionChar125RouteImport.update({
    id: '/recipes/{-$version}',
    path: '/recipes/{-$version}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/recipes.{-$version}.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/{-$version}': typeof RecipesChar123VersionChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/{-$version}': typeof RecipesChar123VersionChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/{-$version}': typeof RecipesChar123VersionChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes/{-$version}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes/{-$version}'
  id: '__root__' | '/' | '/recipes/{-$version}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesChar123VersionChar125Route: typeof RecipesChar123VersionChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/{-$version}': {
      id: '/recipes/{-$version}'
      path: '/recipes/{-$version}'
      fullPath: '/recipes/{-$version}'
      preLoaderRoute: typeof RecipesChar123VersionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesChar123VersionChar125Route: RecipesChar123VersionChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
